import type { ProcessedNews } from "./claude";
import type { RawNewsItem } from "./rssFetcher";
import { getDomainName } from "./feeds";

export async function newsExists(dbUrl: string, url: string): Promise<boolean> {
  const query = `orderBy="url"&equalTo=${encodeURIComponent(JSON.stringify(url))}&limitToFirst=1`;

  const check = async (path: string) => {
    const res = await fetch(`${dbUrl}/${path}.json?${query}`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return false;
    const data = await res.json();
    return !!data && Object.keys(data).length > 0;
  };

  if (await check("Rubalif/toApprove")) return true;
  return check("Rubalif/summariser");
}

export async function addToFirebase(
  dbUrl: string,
  processed: ProcessedNews,
  item: RawNewsItem,
  site: string
): Promise<boolean> {
  const titleEn = processed.titleEnglish || processed.headLineEnglish.slice(0, 45);

  const data = {
    headLineEnglish: processed.headLineEnglish,
    headLineNepali: processed.headLineNepali,
    titleEnglish: processed.titleEnglish,
    titleNepali: processed.titleNepali,
    title: titleEn,
    descriptionEnglish: processed.descriptionEnglish,
    descriptionNepali: processed.descriptionNepali,
    newsSite: item.sourceName || getDomainName(item.url, site),
    author: "Rubalif News Desk",
    url: item.url,
    thumbnail: item.thumbnail || "",
    topicA: processed.topicA,
    topicB: processed.topicB,
    topicC: processed.topicC,
    status: "pending",
    autoGenerated: true,
    createdAt: Date.now(),
  };

  const res = await fetch(`${dbUrl}/Rubalif/toApprove.json`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
    signal: AbortSignal.timeout(15000),
  });

  return res.ok;
}

interface AutomationRunSummary {
  added: number;
  alreadyExists: number;
  errors: number;
  log: string[];
  finishedAt: string;
}

const MAX_LOGGED_RUNS = 20;

export async function logAutomationRun(
  dbUrl: string,
  result: AutomationRunSummary,
  trigger: "cron" | "manual",
  triggeredBy?: string
): Promise<void> {
  try {
    await fetch(`${dbUrl}/Rubalif/automationRuns.json`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...result, trigger, triggeredBy: triggeredBy || null }),
      signal: AbortSignal.timeout(10000),
    });

    const res = await fetch(
      `${dbUrl}/Rubalif/automationRuns.json?shallow=true`,
      { signal: AbortSignal.timeout(10000) }
    );
    if (!res.ok) return;
    const keys = Object.keys((await res.json()) || {}).sort();
    const toDelete = keys.slice(0, Math.max(0, keys.length - MAX_LOGGED_RUNS));
    await Promise.all(
      toDelete.map((k) =>
        fetch(`${dbUrl}/Rubalif/automationRuns/${k}.json`, {
          method: "DELETE",
          signal: AbortSignal.timeout(10000),
        }).catch(() => {})
      )
    );
  } catch {
    // logging failures shouldn't break the automation pipeline itself
  }
}
