import type { ProcessedNews } from "./claude";
import type { RawNewsItem } from "./rssFetcher";
import { getDomainName } from "./feeds";

export async function newsExists(dbUrl: string, url: string): Promise<boolean> {
  const query = `orderBy="url"&equalTo=${encodeURIComponent(JSON.stringify(url))}&limitToFirst=1`;

  const check = async (path: string) => {
    const res = await fetch(`${dbUrl}/${path}.json?${query}`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return false;
    const data = await res.json();
    return !!data && Object.keys(data).length > 0;
  };

  if (await check("Rubalif/toApprove")) return true;
  return check("Rubalif/summariser");
}

export async function getExistingTitles(dbUrl: string): Promise<string[]> {
  const fetchTitles = async (path: string): Promise<string[]> => {
    const res = await fetch(`${dbUrl}/${path}.json`, { signal: AbortSignal.timeout(15000) });
    if (!res.ok) return [];
    const data = await res.json();
    if (!data) return [];
    return Object.values(data as Record<string, { headLineEnglish?: string; title?: string }>)
      .map((n) => n.headLineEnglish || n.title || "")
      .filter(Boolean);
  };

  const [pending, published] = await Promise.all([
    fetchTitles("Rubalif/toApprove"),
    fetchTitles("Rubalif/summariser"),
  ]);
  return [...pending, ...published];
}

export async function publishDueScheduled(dbUrl: string): Promise<number> {
  const res = await fetch(`${dbUrl}/Rubalif/toApprove.json`, { signal: AbortSignal.timeout(15000) });
  if (!res.ok) return 0;
  const data = await res.json();
  if (!data) return 0;

  const now = Date.now();
  let published = 0;

  for (const [key, n] of Object.entries(
    data as Record<
      string,
      Record<string, string | number | boolean | undefined> & {
        status?: string;
        publishAt?: number;
      }
    >
  )) {
    if (n.status !== "scheduled" || !n.publishAt || n.publishAt > now) continue;

    const headEn = (n.headLineEnglish as string) || (n.titleEnglish as string) || "";
    const putRes = await fetch(`${dbUrl}/Rubalif/summariser/${key}.json`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        headLineEnglish: headEn,
        headLineNepali: n.headLineNepali || n.titleNepali || "",
        titleEnglish: n.titleEnglish || n.headLineEnglish || "",
        titleNepali: n.titleNepali || n.headLineNepali || "",
        title: n.titleEnglish || headEn,
        descriptionEnglish: n.descriptionEnglish || "",
        descriptionNepali: n.descriptionNepali || "",
        newsSite: n.newsSite || "",
        author: n.author || "",
        url: n.url || "",
        thumbnail: n.thumbnail || n.thumb || "",
        autoGenerated: n.autoGenerated || false,
        topicA: n.topicA || "",
        topicB: n.topicB || "",
        topicC: n.topicC || "",
        status: "posted",
      }),
      signal: AbortSignal.timeout(15000),
    });
    if (!putRes.ok) continue;

    await fetch(`${dbUrl}/Rubalif/toApprove/${key}.json`, {
      method: "DELETE",
      signal: AbortSignal.timeout(10000),
    });
    published++;
  }

  return published;
}

export async function addToFirebase(
  dbUrl: string,
  processed: ProcessedNews,
  item: RawNewsItem,
  site: string
): Promise<boolean> {
  const titleEn = processed.titleEnglish || processed.headLineEnglish.slice(0, 45);

  const data = {
    headLineEnglish: processed.headLineEnglish,
    headLineNepali: processed.headLineNepali,
    titleEnglish: processed.titleEnglish,
    titleNepali: processed.titleNepali,
    title: titleEn,
    descriptionEnglish: processed.descriptionEnglish,
    descriptionNepali: processed.descriptionNepali,
    newsSite: item.sourceName || getDomainName(item.url, site),
    author: "Rubalif News Desk",
    url: item.url,
    thumbnail: item.thumbnail || "",
    topicA: processed.topicA,
    topicB: processed.topicB,
    topicC: processed.topicC,
    status: "pending",
    autoGenerated: true,
    createdAt: Date.now(),
  };

  const res = await fetch(`${dbUrl}/Rubalif/toApprove.json`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
    signal: AbortSignal.timeout(15000),
  });

  return res.ok;
}

interface AutomationRunSummary {
  added: number;
  alreadyExists: number;
  errors: number;
  log: string[];
  finishedAt: string;
}

const MAX_LOGGED_RUNS = 20;

export async function logAutomationRun(
  dbUrl: string,
  result: AutomationRunSummary,
  trigger: "cron" | "manual",
  triggeredBy?: string
): Promise<void> {
  try {
    await fetch(`${dbUrl}/Rubalif/automationRuns.json`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...result, trigger, triggeredBy: triggeredBy || null }),
      signal: AbortSignal.timeout(10000),
    });

    const res = await fetch(
      `${dbUrl}/Rubalif/automationRuns.json?shallow=true`,
      { signal: AbortSignal.timeout(10000) }
    );
    if (!res.ok) return;
    const keys = Object.keys((await res.json()) || {}).sort();
    const toDelete = keys.slice(0, Math.max(0, keys.length - MAX_LOGGED_RUNS));
    await Promise.all(
      toDelete.map((k) =>
        fetch(`${dbUrl}/Rubalif/automationRuns/${k}.json`, {
          method: "DELETE",
          signal: AbortSignal.timeout(10000),
        }).catch(() => {})
      )
    );
  } catch {
    // logging failures shouldn't break the automation pipeline itself
  }
}
