"use client";

import { useMemo, useState, useEffect } from "react";
import type { NewsRecord } from "@/lib/types";
import DonutChart from "./DonutChart";
import BarChart from "./BarChart";

interface DashboardTabProps {
  pending: NewsRecord;
  published: NewsRecord;
  isDark: boolean;
  active: boolean;
  onViewPending: () => void;
}

function timeAgo(ms: number) {
  const diff = Date.now() - ms;
  if (diff < 60000) return "just now";
  if (diff < 3600000) return Math.floor(diff / 60000) + "m ago";
  if (diff < 86400000) return Math.floor(diff / 3600000) + "h ago";
  return Math.floor(diff / 86400000) + "d ago";
}

const STAT_CARDS = [
  { key: "pending", icon: "⏳", label: "Pending Review", sub: "awaiting approval", color: "text-accent bg-accent/10" },
  { key: "pub", icon: "✅", label: "Published", sub: "live on app", color: "text-green-600 dark:text-green-400 bg-green-500/10" },
  { key: "auto", icon: "🤖", label: "Auto Generated", sub: "from RSS feeds", color: "text-blue-600 dark:text-blue-400 bg-blue-500/10" },
  { key: "today", icon: "📅", label: "Added Today", sub: "last 24 hours", color: "text-amber-600 dark:text-amber-400 bg-amber-500/10" },
] as const;

export default function DashboardTab({
  pending,
  published,
  isDark,
  active,
  onViewPending,
}: DashboardTabProps) {
  const [lastUpdate, setLastUpdate] = useState("");

  useEffect(() => {
    setLastUpdate("Updated " + new Date().toLocaleTimeString());
  }, [pending, published]);

  const stats = useMemo(() => {
    const pKeys = Object.keys(pending);
    const pubKeys = Object.keys(published);
    const day24 = Date.now() - 24 * 60 * 60 * 1000;

    const autoCount =
      pKeys.filter((k) => pending[k].autoGenerated).length +
      pubKeys.filter((k) => published[k].autoGenerated).length;

    const todayCount = pubKeys.filter((k) => (published[k].createdAt || 0) > day24).length;

    const siteCounts: Record<string, number> = {};
    pKeys.forEach((k) => {
      const s = pending[k].newsSite || "Unknown";
      siteCounts[s] = (siteCounts[s] || 0) + 1;
    });
    const sortedSites = Object.entries(siteCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 6) as [string, number][];
    const maxSite = sortedSites[0]?.[1] || 1;

    const latest = [...pKeys]
      .filter((k) => (pending[k].createdAt || 0) > 0)
      .sort((a, b) => (pending[a].createdAt || 0) - (pending[b].createdAt || 0))
      .slice(-4)
      .reverse();

    return { pKeys, pubKeys, autoCount, todayCount, sortedSites, maxSite, latest };
  }, [pending, published]);

  if (!active) return null;

  const values = {
    pending: stats.pKeys.length,
    pub: stats.pubKeys.length,
    auto: stats.autoCount,
    today: stats.todayCount,
  };

  const colors = ["#8b1a2b", "#2563eb", "#16a34a", "#d97706", "#7c3aed", "#0891b2"];

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {STAT_CARDS.map((c) => (
          <div
            key={c.key}
            className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900"
          >
            <div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-lg text-base ${c.color}`}>
              {c.icon}
            </div>
            <div className="text-3xl font-extrabold text-neutral-900 dark:text-neutral-100">
              {values[c.key]}
            </div>
            <div className="mt-1 text-xs font-medium text-neutral-500 dark:text-neutral-400">
              {c.label}
            </div>
            <div className="text-[11px] text-neutral-400 dark:text-neutral-600">{c.sub}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
          <div className="mb-3 flex items-center justify-between">
            <div className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">
              📰 News by Source
            </div>
            <div className="rounded-full bg-neutral-100 px-2.5 py-1 text-[10px] text-neutral-400 dark:bg-neutral-800 dark:text-neutral-500">
              Pending queue
            </div>
          </div>
          <DonutChart sites={stats.sortedSites} isDark={isDark} />
        </div>
        <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
          <div className="mb-3 flex items-center justify-between">
            <div className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">
              📊 Overview
            </div>
            <div className="rounded-full bg-neutral-100 px-2.5 py-1 text-[10px] text-neutral-400 dark:bg-neutral-800 dark:text-neutral-500">
              Live data
            </div>
          </div>
          <BarChart
            pending={values.pending}
            published={values.pub}
            autoCount={values.auto}
            todayCount={values.today}
            isDark={isDark}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
          <div className="mb-3 flex items-center justify-between">
            <div className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">
              🏆 Top News Sources
            </div>
            <div className="rounded-full bg-neutral-100 px-2.5 py-1 text-[10px] text-neutral-400 dark:bg-neutral-800 dark:text-neutral-500">
              {values.pending} pending
            </div>
          </div>
          {stats.sortedSites.length === 0 ? (
            <div className="py-2 text-xs text-neutral-400 dark:text-neutral-600">No data yet</div>
          ) : (
            <div className="space-y-2">
              {stats.sortedSites.map(([name, count], i) => (
                <div key={name} className="flex items-center gap-2">
                  <div className="w-28 shrink-0 truncate text-xs font-medium text-neutral-700 dark:text-neutral-300" title={name}>
                    {name}
                  </div>
                  <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800">
                    <div
                      className="h-full rounded-full transition-all"
                      style={{ width: `${Math.round((count / stats.maxSite) * 100)}%`, background: colors[i % colors.length] }}
                    />
                  </div>
                  <div className="w-6 shrink-0 text-right text-[11px] text-neutral-400 dark:text-neutral-500">
                    {count}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
        <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
          <div className="mb-3 flex items-center justify-between">
            <div className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">
              ⏰ Latest Pending
            </div>
            <span
              onClick={onViewPending}
              className="cursor-pointer text-[11px] font-semibold text-accent hover:underline"
            >
              View all →
            </span>
          </div>
          {stats.latest.length === 0 ? (
            <div className="py-2 text-xs text-neutral-400 dark:text-neutral-600">No pending news</div>
          ) : (
            <div className="divide-y divide-neutral-100 dark:divide-neutral-800">
              {stats.latest.map((k) => {
                const n = pending[k];
                const thumb = n.thumbnail || n.thumb || "";
                const title = n.headLineEnglish || n.titleEnglish || n.title || "—";
                return (
                  <div key={k} className="flex items-center gap-2.5 py-2 first:pt-0 last:pb-0">
                    <div className="h-10 w-10 shrink-0 overflow-hidden rounded-lg bg-neutral-100 dark:bg-neutral-800">
                      {thumb ? (
                        <img
                          src={thumb}
                          loading="lazy"
                          className="h-full w-full object-cover"
                          onError={(e) => {
                            e.currentTarget.style.display = "none";
                          }}
                        />
                      ) : (
                        <div className="flex h-full w-full items-center justify-center text-base text-neutral-300 dark:text-neutral-700">
                          📰
                        </div>
                      )}
                    </div>
                    <div className="min-w-0">
                      <div className="line-clamp-2 text-xs font-semibold text-neutral-900 dark:text-neutral-100">
                        {title}
                      </div>
                      <div className="mt-0.5 text-[10px] text-neutral-400 dark:text-neutral-600">
                        {n.newsSite || ""} {n.createdAt ? "· " + timeAgo(n.createdAt) : ""}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-4 rounded-xl border border-neutral-200 bg-white p-3.5 dark:border-neutral-800 dark:bg-neutral-900">
        <div className="h-2 w-2 animate-pulse rounded-full bg-green-500" />
        <span className="text-xs font-semibold text-neutral-900 dark:text-neutral-100">
          Database Connected
        </span>
        <span className="text-[11px] text-neutral-400 dark:text-neutral-600">🌐 Asia Southeast 1</span>
        <span className="text-[11px] text-neutral-400 dark:text-neutral-600">📦 Rubalif News</span>
        <span className="ml-auto text-[11px] text-neutral-400 dark:text-neutral-600">{lastUpdate}</span>
      </div>
    </div>
  );
}
