import { get, ref, remove, set, update } from "firebase/database";
import { ref as sRef, uploadBytesResumable, getDownloadURL } from "firebase/storage";
import { db, storage } from "@/lib/firebase";
import type { NewsItem } from "@/lib/types";

export async function approveNews(key: string) {
  const snap = await get(ref(db, `Rubalif/toApprove/${key}`));
  const n: NewsItem = snap.val();
  await set(ref(db, `Rubalif/summariser/${key}`), {
    headLineEnglish: n.headLineEnglish || n.titleEnglish || "",
    headLineNepali: n.headLineNepali || n.titleNepali || "",
    titleEnglish: n.titleEnglish || n.headLineEnglish || "",
    titleNepali: n.titleNepali || n.headLineNepali || "",
    title: n.titleEnglish || n.headLineEnglish || "",
    descriptionEnglish: n.descriptionEnglish || "",
    descriptionNepali: n.descriptionNepali || "",
    newsSite: n.newsSite || "",
    author: n.author || "",
    url: n.url || "",
    thumbnail: n.thumbnail || n.thumb || "",
    autoGenerated: n.autoGenerated || false,
    topicA: n.topicA || "",
    topicB: n.topicB || "",
    topicC: n.topicC || "",
    status: "posted",
  });
  await remove(ref(db, `Rubalif/toApprove/${key}`));
}

export async function rejectNews(key: string) {
  await remove(ref(db, `Rubalif/toApprove/${key}`));
}

export async function deletePublished(key: string) {
  await remove(ref(db, `Rubalif/summariser/${key}`));
}

export async function fetchNews(key: string, type: "pending" | "published") {
  const snap = await get(
    ref(db, type === "pending" ? `Rubalif/toApprove/${key}` : `Rubalif/summariser/${key}`)
  );
  return (snap.val() || {}) as NewsItem;
}

export async function saveEdit(
  key: string,
  type: "pending" | "published",
  data: Partial<NewsItem>
) {
  await update(
    ref(db, type === "pending" ? `Rubalif/toApprove/${key}` : `Rubalif/summariser/${key}`),
    data
  );
}

export async function submitNews(data: Partial<NewsItem>) {
  const { push } = await import("firebase/database");
  await push(ref(db, "Rubalif/toApprove"), { ...data, createdAt: Date.now() });
}

export function uploadImage(
  file: File,
  onProgress: (pct: number) => void
): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = sRef(storage, `thumbnails/${Date.now()}_${file.name}`);
    const task = uploadBytesResumable(r, file);
    task.on(
      "state_changed",
      (s) => onProgress((s.bytesTransferred / s.totalBytes) * 100),
      reject,
      async () => {
        const url = await getDownloadURL(task.snapshot.ref);
        resolve(url);
      }
    );
  });
}
